from typing import Any

class OidcExchange:
    def __init__(self, *, config: str | None = None, config_string: str | None = None) -> None: ...
    def handle_request_sync(self, request: dict[str, Any]) -> dict[str, Any]: ...
    async def handle_request(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def asgi_app(self) -> Any: ...
    def wsgi_app(self) -> Any: ...
    def shutdown(self) -> None: ...
